name: 'GSA/grace-config'
description: 'Provides a baseline configuration for AWS Config'
license: cc0-1.0
openSourceProject: 1
governmentWideReuseProject: 1
tags:
    - open-source
    - opensource
    - grace
    - devsecops
contact:
    email: grace-staff@gsa.gov
